apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparklight-raffle-workspace-pvc
  labels:
    app: sparklight-raffle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
