apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sparklight-raffle-pipeline
  labels:
    app: sparklight-raffle
spec:
  params:
    - name: git-url
      type: string
      description: The Git repository URL
    - name: git-revision
      type: string
      description: The Git revision to build
      default: main
    - name: image-name
      type: string
      description: The name of the image to build
      default: sparklight-raffle
  workspaces:
    - name: shared-workspace
      description: Workspace for source code and build artifacts
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image
      taskRef:
        name: s2i-nodejs
        kind: ClusterTask
      runAfter:
        - git-clone
      params:
        - name: VERSION
          value: "20-ubi8"
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.image-name):latest
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            oc set image deployment/$(params.image-name) \
              $(params.image-name)=image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.image-name):latest
            oc rollout status deployment/$(params.image-name) --timeout=300s
